(function($){$.fn.scrollerota=function(options){var defaults={speed:1200,timer:7000,slideshow:true,easing:'swing'};var options=$.extend(defaults,options);return this.each(function(){var obj,images,texts,first,last,imglimit,txtlimit,itemNum,itemWidth,itemHeight,totalWidth,totalHeight,txtTop,imgLeft,txtMove,imgMove;obj=$(this);images=obj.find("ul.images");texts=obj.find("ul.text");itemWidth=$(this).outerWidth();itemHeight=$(this).outerHeight()
first=images.find("li:first");last=images.find("li:last");first.clone().appendTo(images);last.clone().prependTo(images);first=texts.find("li:first");last=texts.find("li:last");first.clone().appendTo(texts);last.clone().prependTo(texts);itemNum=images.find("li").length;totalWidth=itemNum*itemWidth;totalHeight=itemNum*itemHeight;imglimit=-((itemNum-1)*itemWidth);txtlimit=-((itemNum-1)*itemHeight);images.css({width:totalWidth+"px",height:itemHeight+"px",left:-itemWidth+"px"}).find("li").css({width:itemWidth+"px",height:itemHeight+"px"});texts.css({height:totalHeight+"px",top:-itemHeight+"px"}).find("li").css({height:itemHeight+"px"});if(options.slideshow){loop=setTimeout(function(){autoScroll(1,1);},options.timer);obj.append('<div class="controls"><a href="javascript:void(0)" class="prev"></a> <a href="javascript:void(0)" class="play"></a> <a href="javascript:void(0)" class="pause"></a> <a href="javascript:void(0)" class="next"></a></div>')
obj.find(".pause").live("click",function(){clearTimeout(loop);obj.find(".play, .pause").toggle();});obj.find(".play").live("click",function(){loop=setTimeout(function(){autoScroll(1,1);},options.timer);obj.find(".play, .pause").toggle();});}else{obj.append('<div class="controls"><a href="javascript:void(0)" class="prev"></a> <a href="javascript:void(0)" class="next"></a></div>')}
obj.find(".next, .prev").live("click",function(){if($(this).hasClass("next")){autoScroll(1,0);}else{autoScroll(0,0);}
if(options.slideshow){clearTimeout(loop);obj.find(".play").show();obj.find(".pause").hide();}});function autoScroll(next,auto){txtTop=texts.css('top').replace("px","");imgLeft=images.css('left').replace("px","");txtMove=(next)?txtTop-itemHeight:parseInt(txtTop)+parseInt(itemHeight);imgMove=(next)?imgLeft-itemWidth:parseInt(imgLeft)+parseInt(itemWidth);texts.not(':animated').animate({top:txtMove+"px"},options.speed,options.easing,function(){if(txtMove==txtlimit){texts.css({top:-itemHeight+"px"});}
if(txtMove==0){texts.css({top:(txtlimit+itemHeight)+"px"});}});images.not(':animated').animate({left:imgMove+"px"},options.speed,options.easing,function(){if(imgMove==imglimit){images.css({left:-itemWidth+"px"});}
if(imgMove==0){images.css({left:(imglimit+itemWidth)+"px"});}});if(auto&&options.slideshow){loop=setTimeout(function(){autoScroll(1,1);},options.timer);}}});};

$("#scrollerota").scrollerota().css({visibility:'visible'});
})(jQuery);